#!/usr/bin/env python3
"""A stand-in for kicad-cli, used by tests/smoke.py.

Implements just the surface kdif drives - `version`, `pcb export svg` and
`sch export svg` - and writes a tiny SVG that has everything the export
pipeline reads back out: a physical width/height pair, a viewBox, and the
<title>/<desc>/comment metadata that clean_svg() is supposed to strip. The
non-ASCII text element is there on purpose: it is what makes the smoke test
fail if any read/write in kdif falls back to the locale encoding instead of
UTF-8 (which is what happens on a non-English Windows).

This keeps the smoke test runnable on CI runners without a KiCad install, on
every platform. It says nothing about whether real kicad-cli output renders
correctly - only that git extraction, SVG post-processing, HTML assembly and
the process/encoding plumbing around them work.
"""

import sys
from pathlib import Path

SVG = ('<?xml version="1.0" encoding="UTF-8"?>\n'
       '<svg xmlns="http://www.w3.org/2000/svg" width="100.0mm" height="80.0mm" '
       'viewBox="0 0 100 80">'
       '<title>fake</title><desc>generated by tests/fake_kicad_cli.py</desc>'
       '<!-- volatile comment -->'
       '<rect x="10" y="10" width="60" height="40" fill="black"/>'
       '<text x="12" y="70">схема / 図面</text>'
       '</svg>\n')


def main(argv):
    if argv[:1] == ["version"]:
        print("9.0.1")
        return 0
    if "--output" not in argv:
        sys.exit(f"fake kicad-cli: no --output in {argv!r}")
    out = Path(argv[argv.index("--output") + 1])

    if argv[:3] == ["pcb", "export", "svg"]:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(SVG, encoding="utf-8")
        return 0
    if argv[:3] == ["sch", "export", "svg"]:
        # kicad-cli plots one SVG per page: <root>.svg, <root>-<Sheet>.svg, ...
        root = Path(argv[-1])
        out.mkdir(parents=True, exist_ok=True)
        names = [root.stem + ".svg"]
        text = root.read_text(encoding="utf-8", errors="replace")
        for line in text.splitlines():
            if '"Sheetname"' in line or '"Sheet name"' in line:
                sheet = line.split('"')[3]
                names.append(f"{root.stem}-{sheet}.svg")
        for name in names:
            (out / name).write_text(SVG, encoding="utf-8")
        return 0
    sys.exit(f"fake kicad-cli: unexpected argv {argv!r}")


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
